name: Regression Testing

on: [push]

permissions:
  contents: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m venv ./venv
        . ./venv/bin/activate
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Run Regression Tests and Save JUnit Report
      run: |
        . ./venv/bin/activate
        pytest -vvv --junitxml=reports/junit-report.xml
    - name: Publish JUnit Test Report
      uses: mikepenz/action-junit-report@v3
      with:
        report_paths: reports/junit-report.xml
